version: '3.3'

services:
  django_server:
    build:
      context: ./
      dockerfile: compose/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  worker_triggers:
    build:
      context: ./
      dockerfile: compose/Dockerfile
    command: celery -A movies_blog worker -Q triggers -P gevent -c 100 -l info -E -n green@%h --without-mingle --without-gossip
    volumes:
      - .:/app

  worker_green:
    build:
      context: ./
      dockerfile: compose/Dockerfile
    command: celery -A movies_blog worker -Q green -P gevent -c 100 -l info -E -n green@%h --without-mingle --without-gossip
    volumes:
      - .:/app

  worker_database:
    build:
      context: ./
      dockerfile: compose/Dockerfile
    command: celery -A movies_blog worker -Q database -P gevent -c 50 -l info -E -n database@%h --without-mingle --without-gossip

    volumes:
      - .:/app

  worker_rate_limit_grp0:
    build:
      context: ./
      dockerfile: compose/Dockerfile
    command: celery -A movies_blog worker -Q rate_limit_grp0 -P gevent -c 100 -l info -E --prefetch-multiplier=1 -n ratelimit_grp0@%h --without-mingle --without-gossip

    volumes:
      - .:/app

  worker_rate_limit_grp1:
    build:
      context: ./
      dockerfile: compose/Dockerfile
    command: celery -A movies_blog worker -Q rate_limit_grp1 -P gevent -c 100 -l info -E --prefetch-multiplier=1 -n ratelimit_grp0@%h --without-mingle --without-gossip

    volumes:
      - .:/app

  flower:
    build:
      context: ./
      dockerfile: compose/Dockerfile
    command: celery -A movies_blog flower --max_tasks=100000 --purge_offline_workers=180
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    ports:
      - "5555:5555"
      
  celery_beat:
    build:
      context: ./
      dockerfile: compose/Dockerfile
    command: celery -A movies_blog beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
      
  postgres_db:
    image: postgres:13
    command: postgres -B 160MB -N 800
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DEFAULT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DEFAULT_POSTGRES_PASSWORD}
    env_file: .env
    restart: unless-stopped

  redis:
    image: redis:6.2
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
