# Generated by Django 4.2 on 2023-04-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterboxd_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularreviewmodel',
            name='review',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='recentreviewmodel',
            name='review',
            field=models.TextField(max_length=800),
        ),
    ]
