# Generated by Django 4.2 on 2023-04-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterboxd_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
