# Generated by Django 4.2 on 2023-04-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterboxd_scraper', '0002_alter_popularreviewmodel_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='poster_url',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='resized_poster',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='popularreviewmodel',
            name='name',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='popularreviewmodel',
            name='rating',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='recentreviewmodel',
            name='name',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='recentreviewmodel',
            name='rating',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
