# Generated by Django 4.2 on 2023-04-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterboxd_scraper', '0003_alter_imagemodel_poster_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='extraction_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='extraction_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='popularreviewmodel',
            name='extraction_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recentreviewmodel',
            name='extraction_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='statsmodel',
            name='extraction_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
